# Generated by Django 2.0 on 2017-12-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='id',
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
